namespace APPDEV_PROJECT.Models
{
    public class InfoPage_Client_ViewModel
    {
        // we did not put the guid part because we want the id tyo be automatically generated by the database
        public string LName { get; set; }

        public string FName { get; set; }
        public string Mname { get; set; }

        public string Email { get; set; }

       // public string PasswordHash { get; set; } = string.Empty;

        public DateTime DateOfBirth { get; set; }

        public string Sex { get; set; }

        public string PhoneNumber { get; set; }

        public string Address { get; set; }

        public string FullName => $"{FName} {LName}";


    }
}
